import { Talk } from "@/domains/Talk";

export const talks: Talk[] = [
  {
    id: 3,
    slug: "ethdenver-2026",
    title: "Behavior-Based Security for the Next Billion On-Chain Users",
    event: "ETHDenver",
    organizerUrl: "https://www.ethdenver.com/",
    location: "Denver, Colorado",
    country: "United States",
    date: "February 20, 2026",
    uploadDate: "2026-02-20T12:00:00Z",
    offers: {
      price: "0",
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      url: "https://navarrolajous.com/talks/ethdenver-2026",
    },
    description:
      "This talk presents a practical framework for detecting malicious token launches by analyzing on-chain behavioral patterns. Instead of waiting for user reports or post-exploit analysis, Rodrigo demonstrates how to identify threats within seconds of deployment using six core behavioral signals—sniper coordination, deployer history, fund flow tracing, timing patterns, retention analysis, and confidence scoring—giving wallets, DEXes, and researchers actionable tools to protect the next billion on-chain users.",
    topics: [
      "Blockchain Security",
      "Behavioral Analysis",
      "Threat Detection",
      "Smart Contract Security",
      "Web3 Security",
      "On-Chain Analytics",
      "Rug Pull Prevention",
    ],
    links: {
      slides: "/assets/talks/ethdenver-behavior-based-security.pdf",
      video: "https://youtu.be/GENujsJ3szI",
    },
    banner: "/talks/ETHDenver_2026_Banner_Compressed.jpg",
  },
  {
    id: 1,
    slug: "dunecon-2025",
    title: "Patterns in Chaos: Cross-Chain Forensics at Scale",
    event: "DuneCon 25",
    organizerUrl: "https://dune.com/dunecon/",
    location: "Devconnect Buenos Aires",
    country: "Argentina",
    date: "November 19, 2025",
    uploadDate: "2025-11-19T12:00:00Z",
    offers: {
      price: "0",
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      url: "https://navarrolajous.com/talks/dunecon-2025",
    },
    description:
      "Attackers behave consistently across every chain, even when the ecosystems look chaotic. In this talk, Rodrigo breaks down the five behavioral patterns that reveal scams and exploits long before they happen—sniper bot dynamics, cross-chain identity leaks, dangerous function signature pairings, large-scale behavioral spam attacks, and bonding curve concentration risks. Using real multi-chain data, he shows how these patterns let Webacy detect threats at deploy-time instead of after the damage, giving users and protocols an early-warning system for on-chain risk.",
    topics: [
      "Blockchain Forensics",
      "Cross-Chain Security",
      "Threat Detection",
      "Behavioral Analysis",
      "Smart Contract Security",
      "Web3 Security",
      "Data Analytics",
    ],
    links: {
      slides: "/assets/talks/dunecon-cross-chain-forensics.pdf",
      video: "https://youtu.be/2t7ICJPKWnE",
    },
    banner: "/talks/dunecon-banner.jpeg",
  },
  {
    id: 2,
    slug: "defi-security-summit-2025",
    title: "AI and the Future of On-Chain Trust and Safety",
    event: "DeFi Security Summit",
    organizerUrl: "https://defisecuritysummit.org/",
    location: "Devconnect Buenos Aires",
    country: "Argentina",
    date: "November 21, 2025",
    uploadDate: "2025-11-21T12:00:00Z",
    offers: {
      price: "0",
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      url: "https://navarrolajous.com/talks/defi-security-summit-2025",
    },
    description:
      "DeFi security has traditionally focused on post-incident forensics and code-level audits. This talk introduces a new attacker-behavior threat model designed for EVM ecosystems, built on repeatable patterns that appear before an exploit executes. Rodrigo walks through pre-deployment signals, attacker clustering, transaction-intent mismatches, and cross-actor correlations that reveal malicious intent early. The session equips protocols, wallets, and infra teams with practical methods to anticipate and block attacks at the moment of deployment, enabling a more proactive security posture across Ethereum and L2s.",
    topics: [
      "AI",
      "Machine Learning",
      "Web3 Security",
      "Blockchain",
      "Threat Detection",
      "Smart Contract Auditing",
      "On-Chain Analytics",
      "Rug Pull Prevention",
    ],
    links: {
      slides: "/assets/talks/dss-ai-onchain-trust-safety.pdf",
      video: "https://www.youtube.com/watch?v=9wq2BhjKAFI",
    },
    banner: "/talks/dss-banner.jpeg",
  },
];
